version: '3.1'
services:
  dvwa:
    build: .
    ports:
      - 80:80
    links:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
    volumes:
      - ./database/init.docker.sql:/docker-entrypoint-initdb.d/init.sql

